/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.testunited.examples.learnright.provisioning.test.api;

import io.restassured.response.Response;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.TestInstance.Lifecycle;

@TestInstance(Lifecycle.PER_CLASS)
public class GET_All_Test extends ProvisioningApiTestBase{
	
	@BeforeEach
	@Override
	public void setup() {
		super.setup();
	}

	@Test()
	public void success_statuscode() {
		Response response = get("/");
		response.then().assertThat().statusCode(200);
	}

	@Test()
	public void success_bodylength() {
		get("/").then().statusCode(200).assertThat().body("$", hasSize(0));
	}
}
